// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: building.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_building_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_building_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "street.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_building_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_building_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_building_2eproto;
class Building;
struct BuildingDefaultTypeInternal;
extern BuildingDefaultTypeInternal _Building_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Building final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Building) */ {
 public:
  inline Building() : Building(nullptr) {}
  ~Building() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Building(
      ::google::protobuf::internal::ConstantInitialized);

  inline Building(const Building& from) : Building(nullptr, from) {}
  inline Building(Building&& from) noexcept
      : Building(nullptr, std::move(from)) {}
  inline Building& operator=(const Building& from) {
    CopyFrom(from);
    return *this;
  }
  inline Building& operator=(Building&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Building& default_instance() {
    return *internal_default_instance();
  }
  static inline const Building* internal_default_instance() {
    return reinterpret_cast<const Building*>(
        &_Building_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Building& a, Building& b) { a.Swap(&b); }
  inline void Swap(Building* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Building* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Building* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<Building>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Building& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Building& from) { Building::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Building* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Building"; }

 protected:
  explicit Building(::google::protobuf::Arena* arena);
  Building(::google::protobuf::Arena* arena, const Building& from);
  Building(::google::protobuf::Arena* arena, Building&& from) noexcept
      : Building(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBuildingNameFieldNumber = 1,
    kStreetFieldNumber = 3,
    kBuildingNumberFieldNumber = 2,
  };
  // string buildingName = 1;
  void clear_buildingname() ;
  const std::string& buildingname() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_buildingname(Arg_&& arg, Args_... args);
  std::string* mutable_buildingname();
  PROTOBUF_NODISCARD std::string* release_buildingname();
  void set_allocated_buildingname(std::string* value);

  private:
  const std::string& _internal_buildingname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_buildingname(
      const std::string& value);
  std::string* _internal_mutable_buildingname();

  public:
  // .Street street = 3;
  bool has_street() const;
  void clear_street() ;
  const ::Street& street() const;
  PROTOBUF_NODISCARD ::Street* release_street();
  ::Street* mutable_street();
  void set_allocated_street(::Street* value);
  void unsafe_arena_set_allocated_street(::Street* value);
  ::Street* unsafe_arena_release_street();

  private:
  const ::Street& _internal_street() const;
  ::Street* _internal_mutable_street();

  public:
  // uint32 buildingNumber = 2;
  void clear_buildingnumber() ;
  ::uint32_t buildingnumber() const;
  void set_buildingnumber(::uint32_t value);

  private:
  ::uint32_t _internal_buildingnumber() const;
  void _internal_set_buildingnumber(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Building)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      29, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Building_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Building& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr buildingname_;
    ::Street* street_;
    ::uint32_t buildingnumber_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_building_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Building

// string buildingName = 1;
inline void Building::clear_buildingname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.buildingname_.ClearToEmpty();
}
inline const std::string& Building::buildingname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Building.buildingName)
  return _internal_buildingname();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Building::set_buildingname(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.buildingname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Building.buildingName)
}
inline std::string* Building::mutable_buildingname() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_buildingname();
  // @@protoc_insertion_point(field_mutable:Building.buildingName)
  return _s;
}
inline const std::string& Building::_internal_buildingname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.buildingname_.Get();
}
inline void Building::_internal_set_buildingname(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.buildingname_.Set(value, GetArena());
}
inline std::string* Building::_internal_mutable_buildingname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.buildingname_.Mutable( GetArena());
}
inline std::string* Building::release_buildingname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Building.buildingName)
  return _impl_.buildingname_.Release();
}
inline void Building::set_allocated_buildingname(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.buildingname_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.buildingname_.IsDefault()) {
          _impl_.buildingname_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Building.buildingName)
}

// uint32 buildingNumber = 2;
inline void Building::clear_buildingnumber() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.buildingnumber_ = 0u;
}
inline ::uint32_t Building::buildingnumber() const {
  // @@protoc_insertion_point(field_get:Building.buildingNumber)
  return _internal_buildingnumber();
}
inline void Building::set_buildingnumber(::uint32_t value) {
  _internal_set_buildingnumber(value);
  // @@protoc_insertion_point(field_set:Building.buildingNumber)
}
inline ::uint32_t Building::_internal_buildingnumber() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.buildingnumber_;
}
inline void Building::_internal_set_buildingnumber(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.buildingnumber_ = value;
}

// .Street street = 3;
inline bool Building::has_street() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.street_ != nullptr);
  return value;
}
inline const ::Street& Building::_internal_street() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Street* p = _impl_.street_;
  return p != nullptr ? *p : reinterpret_cast<const ::Street&>(::_Street_default_instance_);
}
inline const ::Street& Building::street() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Building.street)
  return _internal_street();
}
inline void Building::unsafe_arena_set_allocated_street(::Street* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.street_);
  }
  _impl_.street_ = reinterpret_cast<::Street*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Building.street)
}
inline ::Street* Building::release_street() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Street* released = _impl_.street_;
  _impl_.street_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::Street* Building::unsafe_arena_release_street() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Building.street)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Street* temp = _impl_.street_;
  _impl_.street_ = nullptr;
  return temp;
}
inline ::Street* Building::_internal_mutable_street() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.street_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Street>(GetArena());
    _impl_.street_ = reinterpret_cast<::Street*>(p);
  }
  return _impl_.street_;
}
inline ::Street* Building::mutable_street() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Street* _msg = _internal_mutable_street();
  // @@protoc_insertion_point(field_mutable:Building.street)
  return _msg;
}
inline void Building::set_allocated_street(::Street* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.street_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.street_ = reinterpret_cast<::Street*>(value);
  // @@protoc_insertion_point(field_set_allocated:Building.street)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_building_2eproto_2epb_2eh
